// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: api/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemType задаёт тип хранимого секрета.
type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED ItemType = 0 // тип не задан
	ItemType_ITEM_TYPE_CREDENTIALS ItemType = 1 // пара логин/пароль
	ItemType_ITEM_TYPE_TEXT        ItemType = 2 // произвольный текст
	ItemType_ITEM_TYPE_BINARY      ItemType = 3 // произвольные бинарные данные
	ItemType_ITEM_TYPE_CARD        ItemType = 4 // данные банковской карты
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "ITEM_TYPE_CREDENTIALS",
		2: "ITEM_TYPE_TEXT",
		3: "ITEM_TYPE_BINARY",
		4: "ITEM_TYPE_CARD",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED": 0,
		"ITEM_TYPE_CREDENTIALS": 1,
		"ITEM_TYPE_TEXT":        2,
		"ITEM_TYPE_BINARY":      3,
		"ITEM_TYPE_CARD":        4,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_keeper_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_api_keeper_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{0}
}

// Item описывает один зашифрованный секрет.
// Поле ciphertext шифруется клиентом до отправки; сервер его не расшифровывает.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // идентификатор элемента
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=keeper.ItemType" json:"type,omitempty"`       // тип секрета
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // человекочитаемое имя (не секрет)
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                 // AES-256-GCM шифртекст полезной нагрузки
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                     // произвольные текстовые метаданные (не секрет)
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`                      // версия элемента для разрешения конфликтов
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix-время последнего изменения (мс)
	Deleted       bool                   `protobuf:"varint,8,opt,name=deleted,proto3" json:"deleted,omitempty"`                      // признак удаления (tombstone)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Item) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Item) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Item) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Item) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// RegisterRequest — запрос регистрации нового пользователя.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // мастер-пароль, передаётся по защищённому каналу и не хранится в открытом виде
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterResponse возвращает токен и соль для деривации ключа шифрования на клиенте.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                    // bearer-токен авторизации
	EncSalt       []byte                 `protobuf:"bytes,2,opt,name=enc_salt,json=encSalt,proto3" json:"enc_salt,omitempty"` // соль для PBKDF2-деривации ключа шифрования
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetEncSalt() []byte {
	if x != nil {
		return x.EncSalt
	}
	return nil
}

// LoginRequest — запрос аутентификации пользователя.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse возвращает токен и соль шифрования.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	EncSalt       []byte                 `protobuf:"bytes,2,opt,name=enc_salt,json=encSalt,proto3" json:"enc_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetEncSalt() []byte {
	if x != nil {
		return x.EncSalt
	}
	return nil
}

// UpsertItemRequest создаёт или обновляет элемент (пустой id => создание).
type UpsertItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertItemRequest) Reset() {
	*x = UpsertItemRequest{}
	mi := &file_api_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertItemRequest) ProtoMessage() {}

func (x *UpsertItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertItemRequest.ProtoReflect.Descriptor instead.
func (*UpsertItemRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// UpsertItemResponse возвращает присвоенные сервером идентификатор, версию и время изменения.
type UpsertItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertItemResponse) Reset() {
	*x = UpsertItemResponse{}
	mi := &file_api_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertItemResponse) ProtoMessage() {}

func (x *UpsertItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertItemResponse.ProtoReflect.Descriptor instead.
func (*UpsertItemResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertItemResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpsertItemResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetItemRequest запрашивает элемент по идентификатору.
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_api_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetItemResponse возвращает запрошенный элемент.
type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_api_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// DeleteItemRequest помечает элемент удалённым (tombstone).
type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_api_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteItemResponse — подтверждение удаления с новой версией и временем.
type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_api_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteItemResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteItemResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// SyncRequest запрашивает элементы, изменённые после курсора клиента.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"` // курсор: ранее полученный max(updated_at); 0 => полная выгрузка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *SyncRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// SyncResponse возвращает изменённые элементы (включая tombstones) и новый курсор.
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *SyncResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

var File_api_keeper_proto protoreflect.FileDescriptor

const file_api_keeper_proto_rawDesc = "" +
	"\n" +
	"\x10api/keeper.proto\x12\x06keeper\"\xdf\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.keeper.ItemTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\benc_salt\x18\x02 \x01(\fR\aencSalt\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\benc_salt\x18\x02 \x01(\fR\aencSalt\"5\n" +
	"\x11UpsertItemRequest\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.keeper.ItemR\x04item\"]\n" +
	"\x12UpsertItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x0fGetItemResponse\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.keeper.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\"#\n" +
	"\vSyncRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x03R\x05since\"J\n" +
	"\fSyncResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.keeper.ItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor*~\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ITEM_TYPE_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eITEM_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10ITEM_TYPE_BINARY\x10\x03\x12\x12\n" +
	"\x0eITEM_TYPE_CARD\x10\x042\xf6\x02\n" +
	"\x06Keeper\x12=\n" +
	"\bRegister\x12\x17.keeper.RegisterRequest\x1a\x18.keeper.RegisterResponse\x124\n" +
	"\x05Login\x12\x14.keeper.LoginRequest\x1a\x15.keeper.LoginResponse\x12C\n" +
	"\n" +
	"UpsertItem\x12\x19.keeper.UpsertItemRequest\x1a\x1a.keeper.UpsertItemResponse\x12:\n" +
	"\aGetItem\x12\x16.keeper.GetItemRequest\x1a\x17.keeper.GetItemResponse\x12C\n" +
	"\n" +
	"DeleteItem\x12\x19.keeper.DeleteItemRequest\x1a\x1a.keeper.DeleteItemResponse\x121\n" +
	"\x04Sync\x12\x13.keeper.SyncRequest\x1a\x14.keeper.SyncResponseB6Z4github.com/iliaonishchenko/gophkeeper/internal/protob\x06proto3"

var (
	file_api_keeper_proto_rawDescOnce sync.Once
	file_api_keeper_proto_rawDescData []byte
)

func file_api_keeper_proto_rawDescGZIP() []byte {
	file_api_keeper_proto_rawDescOnce.Do(func() {
		file_api_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)))
	})
	return file_api_keeper_proto_rawDescData
}

var file_api_keeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_keeper_proto_goTypes = []any{
	(ItemType)(0),              // 0: keeper.ItemType
	(*Item)(nil),               // 1: keeper.Item
	(*RegisterRequest)(nil),    // 2: keeper.RegisterRequest
	(*RegisterResponse)(nil),   // 3: keeper.RegisterResponse
	(*LoginRequest)(nil),       // 4: keeper.LoginRequest
	(*LoginResponse)(nil),      // 5: keeper.LoginResponse
	(*UpsertItemRequest)(nil),  // 6: keeper.UpsertItemRequest
	(*UpsertItemResponse)(nil), // 7: keeper.UpsertItemResponse
	(*GetItemRequest)(nil),     // 8: keeper.GetItemRequest
	(*GetItemResponse)(nil),    // 9: keeper.GetItemResponse
	(*DeleteItemRequest)(nil),  // 10: keeper.DeleteItemRequest
	(*DeleteItemResponse)(nil), // 11: keeper.DeleteItemResponse
	(*SyncRequest)(nil),        // 12: keeper.SyncRequest
	(*SyncResponse)(nil),       // 13: keeper.SyncResponse
}
var file_api_keeper_proto_depIdxs = []int32{
	0,  // 0: keeper.Item.type:type_name -> keeper.ItemType
	1,  // 1: keeper.UpsertItemRequest.item:type_name -> keeper.Item
	1,  // 2: keeper.GetItemResponse.item:type_name -> keeper.Item
	1,  // 3: keeper.SyncResponse.items:type_name -> keeper.Item
	2,  // 4: keeper.Keeper.Register:input_type -> keeper.RegisterRequest
	4,  // 5: keeper.Keeper.Login:input_type -> keeper.LoginRequest
	6,  // 6: keeper.Keeper.UpsertItem:input_type -> keeper.UpsertItemRequest
	8,  // 7: keeper.Keeper.GetItem:input_type -> keeper.GetItemRequest
	10, // 8: keeper.Keeper.DeleteItem:input_type -> keeper.DeleteItemRequest
	12, // 9: keeper.Keeper.Sync:input_type -> keeper.SyncRequest
	3,  // 10: keeper.Keeper.Register:output_type -> keeper.RegisterResponse
	5,  // 11: keeper.Keeper.Login:output_type -> keeper.LoginResponse
	7,  // 12: keeper.Keeper.UpsertItem:output_type -> keeper.UpsertItemResponse
	9,  // 13: keeper.Keeper.GetItem:output_type -> keeper.GetItemResponse
	11, // 14: keeper.Keeper.DeleteItem:output_type -> keeper.DeleteItemResponse
	13, // 15: keeper.Keeper.Sync:output_type -> keeper.SyncResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_keeper_proto_init() }
func file_api_keeper_proto_init() {
	if File_api_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_keeper_proto_goTypes,
		DependencyIndexes: file_api_keeper_proto_depIdxs,
		EnumInfos:         file_api_keeper_proto_enumTypes,
		MessageInfos:      file_api_keeper_proto_msgTypes,
	}.Build()
	File_api_keeper_proto = out.File
	file_api_keeper_proto_goTypes = nil
	file_api_keeper_proto_depIdxs = nil
}
